[package]
name = "yew-app"
version = "0.1.0"
authors = ["gongbaodd@Inspiron_Ubuntu <gongbaodd@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.13.0", features = ["std_web"] }
